#Generated by Fabric Compiler ( version 2024.2-SP1.2 <build 187561> ) at Tue Dec 30 09:48:27 2025

add_design C:/CPLD/pango/2_Tieta_Feiteng/Tieta_Feiteng_1001_PGC7KD69MBG400/prj/Tieta_M/ipcore/pll_i25M_o50M_025M/pll_i25M_o50M_025M.idf
add_design C:/CPLD/pango/2_Tieta_Feiteng/Tieta_Feiteng_1001_PGC7KD69MBG400/prj/Tieta_M/ipcore/pll_i25M_o50M_o25M/pll_i25M_o50M_o25M.idf
remove_design C:/CPLD/pango/2_Tieta_Feiteng/Tieta_Feiteng_1001_PGC7KD69MBG400/prj/Tieta_M/ipcore/pll_i25M_o50M_025M/pll_i25M_o50M_025M.idf
